[package]
name = "send_and_subscribe"
version = "0.1.0"
authors = ["Zack Slayton <zack@xtify.com>"]
edition = "2021"

[dependencies]
stomp = { path = "../.." }
env_logger = "0.11"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
